import type { Metadata } from "next";
import "./globals.css";
import { exo2Init } from "./utils/Fonts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export { exo2Init } from "./utils/Fonts";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exo2Init.variable}`}>{children}</body>
    </html>
  );
}
