import type { Meta, StoryObj } from "@storybook/react";
import ListViewer from "./ListViewer";
const meta: Meta<typeof ListViewer> = {
  component: ListViewer,
};

export default meta;

export const Default: StoryObj<typeof ListViewer> = {
  args: {
    listViewer: {
      id: "1",
      nameList: "Progress",
      tasks: [
        {
          id: "1",
          nameTask: "Test",
          isDone: true,
          listId: "1",
          parentId: null,
          dateCreated: new Date(),
          description: "test description",
          comments: [
            {
              autor: "1",
              text: "comment 1",
              dateCreated: new Date(),
            },
            {
              autor: "2",
              text: "comment 2",
              dateCreated: new Date(),
            },
          ],
          subTasks: [
            {
              id: "1",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "2",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "3",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "4",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "5",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
          ],
        },
        {
          id: "2",
          nameTask: "Test",
          isDone: false,
          listId: "1",
          parentId: null,
          dateCreated: new Date(),
          description: "test description",
          comments: [
            {
              autor: "1",
              text: "comment 1",
              dateCreated: new Date(),
            },
          ],
          subTasks: [
            {
              id: "1",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "2",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "3",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "4",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "5",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
          ],
        },
        {
          id: "3",
          nameTask: "Test",
          isDone: false,
          listId: "1",
          parentId: null,
          dateCreated: new Date(),
          description: "test description",
          comments: [
            {
              autor: "1",
              text: "comment 1",
              dateCreated: new Date(),
            },
            {
              autor: "2",
              text: "comment 2",
              dateCreated: new Date(),
            },
            {
              autor: "3",
              text: "comment 3",
              dateCreated: new Date(),
            },
          ],
          subTasks: [
            {
              id: "1",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "2",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "3",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "4",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "5",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
          ],
        },
        {
          id: "4",
          nameTask: "Test",
          isDone: true,
          listId: "1",
          parentId: null,
          dateCreated: new Date(),
          description: "test description",
          comments: [
            {
              autor: "1",
              text: "comment 1",
              dateCreated: new Date(),
            },
          ],
          subTasks: [
            {
              id: "1",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "2",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "3",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "4",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "5",
              nameTask: "Test",
              isDone: false,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
          ],
        },
        {
          id: "5",
          nameTask: "Test",
          isDone: true,
          listId: "1",
          parentId: null,
          dateCreated: new Date(),
          description: "test description",
          comments: [
            {
              autor: "1",
              text: "comment 1",
              dateCreated: new Date(),
            },
          ],
          subTasks: [
            {
              id: "1",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "2",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "3",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "4",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
            {
              id: "5",
              nameTask: "Test",
              isDone: true,
              listId: "1",
              parentId: null,
              dateCreated: new Date(),
              description: "",
              comments: [],
              subTasks: [],
            },
          ],
        },
      ],
      ProjectId: "1",
    },
  },
};
